### ISSUE TITLE
malkovich: Assertion `textdomain_inited' failed.

### ISSUE THREAD

**Issue by guystreeter** [hadess/gettext-pseudolocale#7]
When I try to use this with my Python3 applications, I get this assertion:

```
python3: ../gettext-pseudolocale.c:134: malkovich: Assertion `textdomain_inited' failed.
%؜s؜:؜ ؜l؜i؜n؜e؜ ؜%؜d؜:؜  8931 Aborted                 ؜(؜c؜o؜r؜e؜ ؜d؜u؜m؜p؜e؜d؜)؜ python3 src/bin/pianofish
```

I have tested my applications with some other locales, and they seem to work correctly.

**Comment by hadess** [comment]
That means that `textdomain()` was not called before a gettext call was made. Your application should be calling `textdomain()` as early as possible during startup.

Do you have a backtrace of the crash? I'm guessing Python might be responsible here.

**Comment by guystreeter** [comment]
I've searched the web for Python examples using gettext, and very few of them call textdomain(). The documentation I found for textdomain() seems to imply that a default will be used if it isn't called.
Explicitly calling textdomain() didn't help. Then I noticed this:

```
$ LD_PRELOAD=$PL/libgettext-pseudolocale.so python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
python3: ../gettext-pseudolocale.c:134: malkovich: Assertion `textdomain_inited' failed.
Aborted (core dumped)
```

I commented out the assertion in your code, and when I run my application only the text of some GTK standard buttons is pseudo-translated.
I'm very confused :)

**Comment by hadess** [comment]
> Your application should be calling textdomain() as early as possible during startup.

This still holds true. The `textdomain` call is something you're supposed to do in your application, so that gettext calls, inside your application, know what gettext domain to get the translations from.

Is your application translated? How is it translated?

**Comment by guystreeter** [comment]
My code uses the _("quoted text") form, and uses setup.py to create the .mo files. I have a script that makes a mangled translation for testing.

```
$ LD_PRELOAD=$PL/libgettext-pseudolocale.so python3
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gettext
>>> gettext.textdomain()
'messages'
>>> gettext.textdomain('pianofish')
'pianofish'
>>> import gi
>>> gi.require_version("Gtk", "3.0")
>>> from gi.repository import Gtk
python3: ../gettext-pseudolocale.c:134: malkovich: Assertion `textdomain_inited' failed.
Aborted (core dumped)
```

Calling textdomain() explicitly doesn't help.

**Comment by hadess** [comment]
From https://docs.python.org/3/library/gettext.html :
> The gettext module defines the following API, which is very similar to the GNU gettext API.

The gettext Python module doesn't use the gettext library...

**Comment by hadess** [comment]
I think that somebody would need to reimplement the shared-library as a Python monkey patching module for it to do anything in your Python app.
